services:
  rproxy:
    build:
      context: .
    container_name: rproxy
    environment:
      - NODE_ENV=production
      - PORT=8080
    ports:
      - 8080:8080
    restart: unless-stopped

networks:
  default:
    name: rproxy
